-- AI 호출 횟수 제한용 로그 테이블입니다.
-- 학생 대화 내용은 저장하지 않습니다.
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_user_created_idx
  on public.ai_usage (user_id, created_at desc);

alter table public.ai_usage enable row level security;

-- 정책을 만들지 않습니다.
-- 브라우저 사용자는 이 테이블을 읽거나 쓸 수 없고,
-- Edge Function의 관리자 컨텍스트만 접근합니다.
